/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseItem } from '../../models/page-response-item';

export interface SearchBooks$Params {
  query: string;
  startIndex: number;
  maxResults: number;
  orderBy?: string;
  filter?: string;
}

export function searchBooks(http: HttpClient, rootUrl: string, params: SearchBooks$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseItem>> {
  const rb = new RequestBuilder(rootUrl, searchBooks.PATH, 'get');
  if (params) {
    rb.query('query', params.query, {});
    rb.query('startIndex', params.startIndex, {});
    rb.query('maxResults', params.maxResults, {});
    rb.query('orderBy', params.orderBy, {});
    rb.query('filter', params.filter, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseItem>;
    })
  );
}

searchBooks.PATH = '/googleBooks/search';
