/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LoggedUser } from '../../models/logged-user';

export interface GetLoggedInUser$Params {
}

export function getLoggedInUser(http: HttpClient, rootUrl: string, params?: GetLoggedInUser$Params, context?: HttpContext): Observable<StrictHttpResponse<LoggedUser>> {
  const rb = new RequestBuilder(rootUrl, getLoggedInUser.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LoggedUser>;
    })
  );
}

getLoggedInUser.PATH = '/user/me';
