spring:
  application:
    name: JwtSecurity
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    password: ${SPRING_DATASOURCE_USERNAME}
    username: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true  # Force TLS
          connectiontimeout: 5000  # 5 seconds
          timeout: 5000
          writetimeout: 5000
          ssl:
            protocols: TLSv1.2  # Enforce modern TLS
          quitwait: false  # Faster connection closure
          dns:
            trustall: true  # Skip reverse DNS lookup
          sendpartial: true  # Send emails even if some recipients fail


application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 86400000  # one day
  mailing:
    activation-url: ${ACTIVATION_URL}
  file:
    uploads:
      photos-output-path: ./uploads
  google:
    Book:
      Key: ${BOOK_API_KEY}

allowed:
  origins: ${ALLOWED_ORIGINS}

supabase:
  url: ${SUPABASE_URL}
  Api-key: ${SUPABASE_API_KEY}
  bucket: ${SUPABASE_BUCKET}


