spring:
  application:
    name: JwtSecurity
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    password: ${SPRING_DATASOURCE_USERNAME}
    username: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}  # 16-char app password (no spaces)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000


application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 86400000  # one day
  mailing:
    activation-url: ${ACTIVATION_URL}
  file:
    uploads:
      photos-output-path: ./uploads
  google:
    Book:
      Key: ${BOOK_API_KEY}

allowed:
  origins: ${ALLOWED_ORIGINS}

supabase:
  url: ${SUPABASE_URL}
  Api-key: ${SUPABASE_API_KEY}
  bucket: ${SUPABASE_BUCKET}


