/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AccessInfo {
  accessViewStatus?: string;
  country?: string;
  embeddable?: boolean;
  publicDomain?: boolean;
  quoteSharingAllowed?: boolean;
  textToSpeechPermission?: string;
  viewability?: string;
  webReaderLink?: string;
}
