/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Price } from '../models/price';
export interface SaleInfo {
  buyLink?: string;
  country?: string;
  ebook?: boolean;
  listPrice?: Price;
  retailPrice?: Price;
  saleability?: string;
}
