/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ImageLinks } from '../models/image-links';
import { IndustryIdentifier } from '../models/industry-identifier';
export interface VolumeInfo {
  authors?: Array<string>;
  averageRating?: number;
  canonicalVolumeLink?: string;
  categories?: Array<string>;
  description?: string;
  imageLinks?: ImageLinks;
  industryIdentifiers?: Array<IndustryIdentifier>;
  infoLink?: string;
  language?: string;
  maturityRating?: string;
  pageCount?: number;
  previewLink?: string;
  printType?: string;
  publishedDate?: string;
  publisher?: string;
  ratingsCount?: number;
  subtitle?: string;
  title?: string;
}
